# SPDX-FileCopyrightText: Open Energy Transition gGmbH and contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "walloon-model"
  scenarios:
    file: config/scenarios.yaml

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - adm
  sector_opts:
  - ''
  planning_horizons:
  - 2025
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
# Walloon model: Belgium and electrical neighbors
countries:
- BE
- FR
- GB
- NL
- DE
- LU

electricity:
  custom_powerplants: True
  walloon_reassignment: True
  walloon_potentials: data/walloon/custom_potentials.csv

  extendable_carriers:
    extendable_nuclear_links:
      2040: [BEWAL, BEBRU, BEVLG, FR, DE, GB, NL, LU]
      2050: [BEWAL, BEBRU, BEVLG, FR, DE, GB, NL, LU]

  powerplants_filter: ((DateOut >= 2024) or (DateOut != DateOut)) and not (Country in ['BE'] and Fueltype == 'Nuclear')

# docs
# TODO: PyPSA-Eur merge issue in prepare_sector_network.py
# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror

existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2050]
  threshold_capacity: 0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  mode: custom_busmap_BE
  temporal:
    resolution_elec: False
    resolution_sector: 3000h
  exclude_carriers:
    - nuclear

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  oil_boilers: true
  solid_biomass_import:
    enable: true

costs:
  custom_cost_fn: data/walloon/custom_costs_rc.csv

solving:
  agg_p_nom_limits:
    agg_offwind: true
    agg_solar: true
    agg_nuclear: true
    include_existing: true
    file: data/agg_p_nom_minmax.csv

  constraints:
    CCL: true
